require:
  - rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
   - 'bin/**/*'
   - 'config/**/*'
   - 'db/**/*'
   - 'node_modules/**/*'
   - 'script/**/*'
   - 'spec/rails_helper.rb'
   - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'it', 'define', 'factory']

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'

Metrics/MethodLength:
  Max: 80

Metrics/AbcSize:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/ModuleLength:
  Max: 100
